licenses(["notice"])  # Apache 2

load("//bazel:api_build_system.bzl", "api_proto_library_internal")

api_proto_library_internal(
    name = "session_manager",
    srcs = ["config.proto"],
    visibility = ["//visibility:public"],
)
